# Generated by Django 2.0.7 on 2018-07-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beton', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageblock',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='img/media', verbose_name='Иллюстрация'),
        ),
    ]
