# Generated by Django 2.0.7 on 2018-07-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beton', '0002_auto_20180720_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageblock',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='img/media/%Y/%m/%d', verbose_name='Иллюстрация'),
        ),
    ]
