# Generated by Django 2.0.7 on 2018-07-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beton', '0003_auto_20180720_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpageblock',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Порядок следования на странице'),
        ),
    ]
