# Generated by Django 2.0.7 on 2018-07-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beton', '0004_mainpageblock_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpageblock',
            name='main_test',
        ),
        migrations.AddField(
            model_name='mainpageblock',
            name='main_tesxt',
            field=models.TextField(blank=True, verbose_name='Основной текст'),
        ),
        migrations.AlterField(
            model_name='mainpageblock',
            name='title',
            field=models.TextField(blank=True, verbose_name='Заголовок'),
        ),
    ]
