# Generated by Django 2.0.7 on 2018-07-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beton', '0005_auto_20180720_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpageblock',
            old_name='main_tesxt',
            new_name='main_text',
        ),
    ]
