# Generated by Django 2.0.7 on 2018-07-20 15:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('beton', '0006_auto_20180720_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageblock',
            name='main_text',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Основной текст'),
        ),
    ]
