# Generated by Django 2.0.7 on 2018-07-23 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beton', '0010_service_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deleivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='Заголовок раздела')),
            ],
            options={
                'db_table': 'DELIVERY',
            },
        ),
        migrations.CreateModel(
            name='DeleiveryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='150x300px', upload_to='img/media/%Y/%m/%d', verbose_name='Иллюстрация'),
        ),
        migrations.AlterField(
            model_name='service',
            name='url',
            field=models.CharField(blank=True, default='#', max_length=500, verbose_name='Адрес страницы'),
        ),
        migrations.AddField(
            model_name='deleivery',
            name='illustrations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beton.DeleiveryImage'),
        ),
    ]
