# Generated by Django 2.0.7 on 2018-07-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beton', '0010_service_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='url',
            field=models.CharField(blank=True, default='#', max_length=500, verbose_name='Адрес страницы'),
        ),
    ]
