# Generated by Django 2.0.7 on 2018-07-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beton', '0011_auto_20180720_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='150x300px', upload_to='img/media/%Y/%m/%d', verbose_name='Иллюстрация'),
        ),
    ]
