# Generated by Django 2.0.7 on 2018-07-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beton', '0012_deleiveryimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deleivery',
            name='illustrations',
        ),
        migrations.AddField(
            model_name='deleivery',
            name='illustrations',
            field=models.ManyToManyField(to='beton.DeleiveryImage', verbose_name='Иллюстрации'),
        ),
        migrations.AlterField(
            model_name='deleiveryimage',
            name='image',
            field=models.ImageField(blank=True, help_text='150x300px', upload_to='img/media/%Y/%m/%d', verbose_name='Иллюстрации'),
        ),
    ]
