# Generated by Django 2.0.7 on 2018-07-24 19:03

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('beton', '0013_auto_20180723_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deleivery',
            name='illustrations',
        ),
        migrations.AddField(
            model_name='deleivery',
            name='illustration_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='beton.DeleiveryImage', verbose_name='Иллюстрация 1'),
        ),
        migrations.AddField(
            model_name='deleivery',
            name='main_text',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Основной текст'),
        ),
    ]
