# Generated by Django 2.0.7 on 2018-07-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beton', '0016_auto_20180724_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleiveryPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(blank=True, max_length=60, verbose_name='Населённый пункт')),
                ('price', models.CharField(blank=True, max_length=15, verbose_name='Цена')),
            ],
        ),
    ]
