# Generated by Django 2.0.7 on 2018-07-27 22:55

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('beton', '0019_auto_20180725_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='Заголовок раздела')),
                ('illustration', models.ImageField(blank=True, help_text='150x300px', upload_to='img/media/%Y/%m/%d', verbose_name='Иллюстрация')),
                ('main_text', tinymce.models.HTMLField(blank=True, verbose_name='Основной текст')),
            ],
            options={
                'db_table': 'PRICEPAGE',
            },
        ),
    ]
