# Generated by Django 2.0.7 on 2018-07-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beton', '0020_pricepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='gallery')),
                ('captions', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ['title'],
                'verbose_name_plural': 'Иллюстрации',
                'verbose_name': 'Иллюстрация',
            },
        ),
    ]
