# Generated by Django 2.0.7 on 2018-07-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beton', '0023_galleryextended_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='Название предприятия')),
                ('logo', models.ImageField(blank=True, help_text='150x300px', upload_to='img/media/%Y/%m/%d', verbose_name='Логотип')),
                ('url', models.CharField(blank=True, default='#', max_length=500, verbose_name='Ссылка')),
                ('country', models.CharField(blank=True, default='#', max_length=60, verbose_name='Страна')),
            ],
            options={
                'db_table': 'PARTNERS',
            },
        ),
    ]
