# Generated by Django 2.0.7 on 2018-07-31 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beton', '0024_partners'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partners',
            new_name='Partner',
        ),
    ]
