# Generated by Django 2.0.7 on 2018-07-31 22:56

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20180729_0029'),
        ('taggit', '0002_auto_20150616_2121'),
        ('beton', '0025_auto_20180801_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainGalleryExtended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_extended', to='photologue.Gallery')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Extra fields',
                'verbose_name': 'Extra fields',
            },
        ),
    ]
