# Generated by Django 2.0.7 on 2018-08-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beton', '0026_maingalleryextended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maingalleryextended',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='maingalleryextended',
            name='tags',
        ),
        migrations.DeleteModel(
            name='MainGalleryExtended',
        ),
    ]
