# Generated by Django 2.0.7 on 2018-08-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beton', '0029_auto_20180801_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.ManyToManyField(related_name='_contact_phone_+', to='beton.Phone', verbose_name='Номер телефона'),
        ),
    ]
