# Generated by Django 2.0.7 on 2018-08-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beton', '0030_auto_20180801_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Email')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
            ],
            options={
                'db_table': 'Proposal',
            },
        ),
    ]
