# Generated by Django 2.0.7 on 2018-08-03 19:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('beton', '0031_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание требования')),
            ],
            options={
                'db_table': 'REQUIRMENT',
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='Название вакансии')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Описание вакансии')),
                ('salary', models.CharField(blank=True, max_length=40, verbose_name='Зарплата')),
                ('phones', models.CharField(blank=True, max_length=100, verbose_name='Контактный телефон')),
                ('illustration', models.ImageField(blank=True, help_text='150x300px', upload_to='img/media/%Y/%m/%d', verbose_name='Иллюстрация')),
            ],
            options={
                'db_table': 'VACATION',
            },
        ),
        migrations.CreateModel(
            name='WorkingCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание условия работы')),
            ],
            options={
                'db_table': 'WORKINGCONDITION',
            },
        ),
        migrations.AlterModelTable(
            name='proposal',
            table='PROPOSAL',
        ),
        migrations.AddField(
            model_name='vacation',
            name='conditions',
            field=models.ManyToManyField(related_name='_vacation_conditions_+', to='beton.WorkingCondition', verbose_name='Условия работы'),
        ),
        migrations.AddField(
            model_name='vacation',
            name='requirements',
            field=models.ManyToManyField(related_name='_vacation_requirements_+', to='beton.CandidateRequirement', verbose_name='Требования'),
        ),
    ]
