# Generated by Django 2.0.7 on 2018-08-06 19:41

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('beton', '0034_maincementmixes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandSail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Название')),
                ('title_list', tinymce.models.HTMLField(blank=True, verbose_name='Основной текст')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Основной текст')),
                ('title_illustration', models.ImageField(blank=True, help_text='150x300px', upload_to='img/media/%Y/%m/%d', verbose_name='Верхняя иллюстрация')),
                ('main_illustration', models.ImageField(blank=True, help_text='150x300px', upload_to='img/media/%Y/%m/%d', verbose_name='Нижняя иллюстрация')),
            ],
            options={
                'db_table': 'SANDSAIL',
            },
        ),
    ]
