# Generated by Django 2.0.7 on 2018-08-06 20:41

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('beton', '0035_sandsail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrushedStone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Текст')),
                ('illustration', models.ImageField(blank=True, help_text='150x300px', upload_to='img/media/%Y/%m/%d', verbose_name='Верхняя иллюстрация')),
            ],
            options={
                'db_table': 'CRUSHEDSTONE',
            },
        ),
    ]
