# Generated by Django 2.0.7 on 2018-08-06 23:03

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('beton', '0036_crushedstone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reinforced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Текст')),
                ('illustration', models.ImageField(blank=True, help_text='150x300px', upload_to='img/media/%Y/%m/%d', verbose_name='Иллюстрация')),
            ],
            options={
                'db_table': 'REINFORCED',
            },
        ),
        migrations.CreateModel(
            name='ReinforcedPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('volume', models.CharField(blank=True, max_length=200, verbose_name='Объём 1шт м/3')),
                ('price', models.CharField(blank=True, max_length=30, verbose_name='Цена 1шт з ПДВ, грн')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='beton.Reinforced', verbose_name='Тип')),
            ],
            options={
                'db_table': 'REINFORCEDPRICE',
            },
        ),
        migrations.AlterField(
            model_name='crushedstone',
            name='illustration',
            field=models.ImageField(blank=True, help_text='150x300px', upload_to='img/media/%Y/%m/%d', verbose_name='Иллюстрация'),
        ),
    ]
