# Generated by Django 2.0.7 on 2018-08-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beton', '0038_reinforced_extra_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reinforced',
            name='type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Класс для JS'),
        ),
    ]
